parameters:
  learning_rate: [0.1, 0.5]
  n_estimators: [100, 400]
  split_type: ['sum_vols']
  max_depth: [3, 10]
  steps: [10]
  reg_alpha: [0, .5]
  reg_lambda: [0]
  model: ['lightgbm', 'xgboost']